### ISSUE TITLE
Fix the email format in sign-up page

### ISSUE THREAD

**Issue by ShresthaPriya** [12sonam/FreshPicks#1]
I encounter with a issue while running our program. Without the appropriate domain (e.g. domain.com) in email input field, sign up is successful. I tried putting just 123 after @, and even without using domain, the signup is successful. Please, use proper email validation logic and ensure that  sign-up is successful only when using appropriate domain such as (domain.com). Email should be as follow:
Priya12@gmail.com

**Comment by Timalcnabibek** [comment]
The format for email is updated. I have used regex for email where the email should consist of letters and after '@' there should be domain name and after '.' the last part should be 2-5 letters long.
![signup](https://github.com/12sonam/FreshPicks/assets/120554874/3963d24e-05a0-48ed-9c5b-8ceda0a3aae0)
