### ISSUE TITLE
Product updates without filling up the details

### ISSUE THREAD

**Issue by ShresthaPriya** [12sonam/FreshPicks#11]
I have opened the manage product page and tried updating the product. But without filling the form/ with the empty form, while clicking on the update button, the pop up saying "the product details updated successfully" is showing. It might be the validation issue with the functionality of update product. Make it display the error message, also empty details should not be stored in the database.  Upon putting empty details, it should throw the error and the previous details should be displayed as it is.
![image](https://github.com/12sonam/FreshPicks/assets/119417756/82f45157-3eee-4529-b420-3124f5221d63)
![image](https://github.com/12sonam/FreshPicks/assets/119417756/70231d0b-7973-465f-b57f-5d87042cfc30)

**Comment by 12sonam** [comment]
![image](https://github.com/12sonam/FreshPicks/assets/86185394/a838b2e4-ad70-4b5e-9baa-649004a43b51)
from the above code the given issue was solved that it any input field is empty it should throw error message

**Comment by 12sonam** [comment]
![image](https://github.com/12sonam/FreshPicks/assets/86185394/a838b2e4-ad70-4b5e-9baa-649004a43b51)
from the above code the given issue was solved that it any input field is empty it should throw error message

**Comment by 12sonam** [comment]
![image](https://github.com/12sonam/FreshPicks/assets/86185394/a838b2e4-ad70-4b5e-9baa-649004a43b51)
from the above code the given issue was solved that it any input field is empty it should throw error message 
![image](https://github.com/12sonam/FreshPicks/assets/86185394/9bc5fe1e-cbe0-4ed7-99be-36acdfea8258)
