### ISSUE TITLE
Edit farmers details successful with empty field in form

### ISSUE THREAD

**Issue by ShresthaPriya** [12sonam/FreshPicks#12]
I clicked on update button of the farmer management via admin page, and without completely filling up the form, the update is successful, also in the list of the farmers, the fields that I have put empty is displaying empty in the interface as well. There must be some validation issue as well as the empty fields is being stored in database so it is fetching the empty data and displaying in the interface likewise. You can try putting the validation, error message while submitting the form with empty fields and stop database to store the empty fields. 

![image](https://github.com/12sonam/FreshPicks/assets/119417756/ed9c7b3f-ef31-4218-a84d-069bb8151755)
![image](https://github.com/12sonam/FreshPicks/assets/119417756/0b1a11a6-1f0d-4c96-ab46-37714294a7a9)

**Comment by Timalcnabibek** [comment]
This issue is solved. Admin cannot submit the form if any of the field is empty. The admin needs to submit a complete filled form otherwise the form cannot be submitted.
