### ISSUE TITLE
Edit customer successful with empty field in the form

### ISSUE THREAD

**Issue by ShresthaPriya** [12sonam/FreshPicks#13]
I have tried updating the customer details via admin page, but even with the empty field in the form, the update is successful. Also, I think the empty fields are being stored in the database as well as in the interface also the null fields are being reflected. Please try butting some validation on this, give some error message in such case and do not store null values in database. While putting the empty details, throw the error message and display the previous details.

![image](https://github.com/12sonam/FreshPicks/assets/119417756/95a791da-7499-4140-b3fd-5633e23de3c4)
![image](https://github.com/12sonam/FreshPicks/assets/119417756/7f996cb9-465b-44b7-885c-b18cf429cc80)

**Comment by MaskeyRiddhi** [comment]
To address the issue, code was added to upadate.html file to check if certain fields such as username, address, email, and password are empty. If any field is empty, an alert message is displayed to prompt the user to enter the data.
![image](https://github.com/12sonam/FreshPicks/assets/119106952/63935c57-d6c6-4b64-953a-36482dbfc7c0)
