### ISSUE TITLE
Admin Dashboard Inside farmer button farmers details are not align properly elongate it.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#14]
If any problem go through the bug report attached below:

**Comment by Elizasthaaa** [comment]
Initially, there was a problem with the alignment of farmer details inside a button on the admin dashboard. To fix this, the layout was adjusted by removing a grid arrangement, which caused the table displaying the details to elongate, ultimately solving the alignment issue.

Before fixing the issue:
![image](https://github.com/12sonam/FreshPicks/assets/119391309/267f50ec-884e-4a53-9176-5d30faf8d97c)
After fixing the issue:
![image](https://github.com/12sonam/FreshPicks/assets/119391309/a3d469ea-b7c7-4583-8335-067a09a4f6d2)
