### ISSUE TITLE
Inside Customer Dashboard rename the shopnow button to View product.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#15]
if any problem go through the bug report.

**Comment by Elizasthaaa** [comment]
As per the issue, in the customer dashboard there was a shop now which directed to all product list page. So, to fix this issue I changed the button name from shop now to view products by renaming the name in html code.

Ui before fixing the bug:
![image](https://github.com/12sonam/FreshPicks/assets/119391309/d8312670-d8fe-427f-a229-43c5132d0419)
Ui after fixing the bug:
![image](https://github.com/12sonam/FreshPicks/assets/119391309/3b240e78-4dd1-481f-b2c3-88126c145436)
