### ISSUE TITLE
In Customer Dashboard inside the  View all page put cross button so user can return back to  Dashboard.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#16]
If any problem go through the bug report.

**Comment by Elizasthaaa** [comment]
To fix the problem, I made a few changes. First, I added a button on the View All page so users can easily go back to the Customer Dashboard. Then, I made sure the button looks right using CSS and used JSS to make sure it works smoothly when clicked. Now, users can quickly get back to the Dashboard whenever they want.
Ui before fixing the issue:
![image](https://github.com/12sonam/FreshPicks/assets/119391309/3242a390-d53a-4637-84bc-eac705ac5481)
Ui after fixing the issue:
![image](https://github.com/12sonam/FreshPicks/assets/119391309/5ba4e666-72d9-405b-b002-907f36793622)
