### ISSUE TITLE
In Customer Dashboard there is spelling error for Freshpick in footer correct it as Freshpicks.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#17]
In footer part of the Customer Dashboard the spelling of Freshpick is not correct. So it will look  better if the spelling is correct.

**Comment by Elizasthaaa** [comment]
To resolve the issue, I updated the spelling of "Freshpick" to "Freshpicks" in the footer of the Customer Dashboard. 
Ui before fixing the bug:
![image](https://github.com/12sonam/FreshPicks/assets/119391309/fb51ee32-e9ae-46b6-8bfa-4cc45415665e)
Ui after fixing the bug:
![image](https://github.com/12sonam/FreshPicks/assets/119391309/43872319-4682-431f-ae06-6ba9a5de1389)
