### ISSUE TITLE
In Farmer Dashboard inside  add product button in product category remove hover in it.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#18]
If any problem go through the bug report.

**Comment by Elizasthaaa** [comment]
I have addressed issue by removing the unnecessary and visually unappealing hover effect from the "Add Product" button in the Farmer Dashboard's product category section.

Ui before fixing the bug:
![image](https://github.com/12sonam/FreshPicks/assets/119391309/14d8b74e-8c99-4bb6-9417-dd94ae498838)
Ui after fixing the bug:
![image](https://github.com/12sonam/FreshPicks/assets/119391309/85e5dbc3-c79e-4f0e-816a-425f0a60369b)
