### ISSUE TITLE
In Farmer Dashboard inside add product button put a cross button inside it so that user can return back to dashboard.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#19]
if any problem go through the bug report.

**Comment by Elizasthaaa** [comment]
I addressed the issue by implementing a couple of adjustments. Initially, I included a cross button on the "Add product" page to facilitate users in returning to the Farmer Dashboard effortlessly. I ensured the button's appearance was correct using CSS, and I utilized JSS to ensure seamless functionality when clicked. 

Ui before fixing the bug:
![image](https://github.com/12sonam/FreshPicks/assets/119391309/d6ad93f3-1ab4-459e-bccd-d01b1dc5abf9)

Ui after fixing the bug:
![image](https://github.com/12sonam/FreshPicks/assets/119391309/a84a283c-6aa3-427f-b399-8f90740e051f)
