### ISSUE TITLE
Fix this issue: Sign-up successful despite password mismatches in confirmation field.

### ISSUE THREAD

**Issue by ShresthaPriya** [12sonam/FreshPicks#2]
Our sign-up process is allowing users to successfully create an account even when the password is mismatched in password field and password confirmation field. This arises security concerns of our system so, please use proper validation to address this issue and ensure that the sign-up is completed only when password and confirmation password is same.

**Comment by MaskeyRiddhi** [comment]
The issues regarding the sign-up process allowing users to create an account with a mismatched password and password confirmation has been successfully resolved. I have implemented an if condition, that checks if the password and password confirmation fields match before proceeding with the account creation process. This ensures that the user's password and password confirmation are identical. I have thoroughly tested the implementation to ensure that it works as expected.
