### ISSUE TITLE
In Customer Dashboard signout button is not Working.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#20]
If any problem go through bug report.

**Comment by 12sonam** [comment]
![image](https://github.com/12sonam/FreshPicks/assets/86185394/4d09b65b-2ef0-49da-bd67-168b20a04b35)
before when the ok is clicked it dosen't direct to the login page after below update in code 
fixed the sign-out button that when it is clicked it will direct it to the index.html page
![image](https://github.com/12sonam/FreshPicks/assets/86185394/9bc14b23-0cd0-4492-92f2-e3d2aec35e53)
![image](https://github.com/12sonam/FreshPicks/assets/86185394/615c36e7-6543-4927-bf9a-fc0de674dca0)
