### ISSUE TITLE
In Customer Dashboard inside search if the product which is not store in database is searched than error message is not been displayed below search bar. 

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#21]
if any problem go through the bug report.

**Comment by 12sonam** [comment]
![image](https://github.com/12sonam/FreshPicks/assets/86185394/99f2c55b-7903-4b81-b904-5511537a7654)

fixed the code in search.js and now the it shows error message if the product is not found in database

![image](https://github.com/12sonam/FreshPicks/assets/86185394/dbe92ca8-d743-43d1-8578-796475a69642)
