### ISSUE TITLE
In admin dashboard  total number of product is not showing in product page.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#23]
If any problem go through the bug report.

**Comment by Timalcnabibek** [comment]
The number of products is now showing in the product page from admin panel. Before the solution was found, the interface used to hold manually set number of products.


![image](https://github.com/12sonam/FreshPicks/assets/120554874/813c0d13-a995-427a-a889-ea690742542a)


But now it shows the total number of products in the database.


![image](https://github.com/12sonam/FreshPicks/assets/120554874/72d8ab89-293a-4bb4-b307-b930d0e08a0b)
