### ISSUE TITLE
In admin dashboard Farmer is not being deleted inside the farmer page.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#24]
if any problem go through the bug report.

**Comment by Timalcnabibek** [comment]
After making some changes and adding some code, the feature is now working. Admin is now able to delete the farmers.

**Comment by Timalcnabibek** [comment]
After making some changes and adding some code, the feature is now working. Admin is now able to delete the farmers.

Bofore fixing the issue the interface looked like this even after clicking the delete button.

![image](https://github.com/12sonam/FreshPicks/assets/120554874/5b154bf6-d8c7-417e-b636-587c38947304)



After fixing the bug, we can see the verification for deleting the customer.

![image](https://github.com/12sonam/FreshPicks/assets/120554874/0b816811-06ac-40c7-b8ab-3a4e4d68cbb2)
