### ISSUE TITLE
In admin Dashboard sign out is not working.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#25]
If any problem go through the bug report.

**Comment by Timalcnabibek** [comment]
The sign out feature from admin dashboard is now working. Before fixing the bug, even when the sign out button is clicked, it was not showing the confirmation for logging out.
![image](https://github.com/12sonam/FreshPicks/assets/120554874/3026a6cc-b9b8-4673-80cd-38d0f55fbe2b)



but after fixing the bug, the confirmation for sign out is showing



![image](https://github.com/12sonam/FreshPicks/assets/120554874/e9de8cec-aa5d-4de2-ac05-3f1bf87b6cb9)
