### ISSUE TITLE
In admin dashboard in the customer page inside the manage button update button is not redirecting to update page.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#26]
If any problem please go through the bug report.

**Comment by Timalcnabibek** [comment]
The update button in customer page which is in admin panel is now redirecting the page to update.html file after clicking it.

before solving this issue, we could only click on the button and not redirecting it to update.html file
![image](https://github.com/12sonam/FreshPicks/assets/120554874/9512ba86-67d1-44b8-ade8-7282d50d9093)




but after solving the issue, we could open the update.html file after clicking the update button.



![image](https://github.com/12sonam/FreshPicks/assets/120554874/4543f80e-ede3-40c2-a504-f75aa0518b2c)
