### ISSUE TITLE
In Customer dashboard while adding more products to wishlist scrolling feature is not working.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#28]
if any problem go through the bug report.

**Comment by 12sonam** [comment]
![image](https://github.com/12sonam/FreshPicks/assets/86185394/aec3d729-3059-4339-8cba-1479b63ef6d6)


fixed the scroll button in the Wishlist panel adding the scroll button in html 
![image](https://github.com/12sonam/FreshPicks/assets/86185394/b37a8cb1-7dde-406e-9fce-06aa0f80ab98)
and included js code that when the products added to Wishlist goes more then the the panel list height it shows the scroll button 
![image](https://github.com/12sonam/FreshPicks/assets/86185394/ddca0f20-593a-4156-9a7f-cb304c07098c)

![image](https://github.com/12sonam/FreshPicks/assets/86185394/ab015c7e-8733-4e86-b25c-37563694d4d1)
