### ISSUE TITLE
In customer dashboard while adding more products to cart the scrolling feature is not working,

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#29]
if any problem go through the bug report.

**Comment by 12sonam** [comment]
![image](https://github.com/12sonam/FreshPicks/assets/86185394/05458dd5-94c8-40d2-851d-2c32a2ebe95b)


fixed the scroll button in the addtocart panel adding the scroll button in html 
![image](https://github.com/12sonam/FreshPicks/assets/86185394/34efcdb7-6706-48b0-9713-de9e75abb753)

and included js code that when the products added to cart goes more then the the panel list height it shows the scroll button 
![image](https://github.com/12sonam/FreshPicks/assets/86185394/4b120868-01c4-482b-adf1-8211aa5aeaf3)

![image](https://github.com/12sonam/FreshPicks/assets/86185394/3d0c6719-8d98-414f-a950-d1c0944832a1)
