### ISSUE TITLE
Improve password validation for better and strong security

### ISSUE THREAD

**Issue by ShresthaPriya** [12sonam/FreshPicks#3]
While running our program, I faced that our system lacks strong password validation. Even with a simple and normal passwords like 111, AAA, sign-up is successful. Hence, fix this issue by making sure that password meets some criteria such as minimum length (8), mix of letters, numbers and special characters.

**Comment by 12sonam** [comment]
i have fixed the password validation and includes some password format with error message that help user to provide the password according to the password validation format.
![image](https://github.com/12sonam/FreshPicks/assets/86185394/726aa735-a01f-426d-8e02-6d8b0c759505)
![image](https://github.com/12sonam/FreshPicks/assets/86185394/306be10f-2b7c-4b9e-aad8-a0f69c6eb32a)

**Comment by 12sonam** [comment]
![image](https://github.com/12sonam/FreshPicks/assets/86185394/8a98023e-7923-4be5-9410-234ebcb25d28)
