### ISSUE TITLE
In admin login error message is not displayed when trying to login without entering the email and password.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#30]
If any problem go through the bug report.

**Comment by MaskeyRiddhi** [comment]
To resolve this issue, code has been implemented in the adminlogin.js file to verify that fields such as email and password are not left blank. If either field is empty, an error message will be displayed, prompting the user to fill in all fields before attempting to log in.
Before solving the issue:
![image](https://github.com/12sonam/FreshPicks/assets/119106952/fd83aff3-bc33-4676-b887-15f80a016e82)

After solving the issue:
![image](https://github.com/12sonam/FreshPicks/assets/119106952/a9865b2a-2bf0-4829-93a2-c274ed40a7cc)
