### ISSUE TITLE
In farmer dashboard inside product page add navigation bars.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#31]
If any problem go through the bug report.

**Comment by MaskeyRiddhi** [comment]
To resolve the issue, code has been added to the product.html file to include a navigation bar when displaying product details.
Before: 
![image](https://github.com/12sonam/FreshPicks/assets/119106952/18d0d92b-b972-4ca3-87d2-e5ac4e89a085)

After:
![image](https://github.com/12sonam/FreshPicks/assets/119106952/abe5d3a7-234e-40f2-9179-26af66c403bd)
