### ISSUE TITLE
In customer dashboard inside the customer enquiry form if the email format is incorrect Users are able to submit the form. 

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#34]
Anything we write in form can be submitted so make the email to be written in correct format.

**Comment by 12sonam** [comment]
![image](https://github.com/12sonam/FreshPicks/assets/86185394/d97f2a85-0175-4e70-a20c-30fc7f739ca4)
the issue has be solved email validation is used and fixed the issue
![image](https://github.com/12sonam/FreshPicks/assets/86185394/d8f7e8ac-3c79-4df8-bc74-6d39db1eedc9)
