### ISSUE TITLE
In Login page for Customer and farmer proper  error message is not been displayed such as  while trying to login without filling the details.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#35]
if any problem go through the bug report.

**Comment by MaskeyRiddhi** [comment]
To address these issues, I have made modifications to two files: index.html and login.js. I have added an error ID in the HTML file, and in the JS file, I have added code to ensure that fields such as email, password, and roles are not left blank. If any field is empty, an error message will be displayed, prompting the user to complete all fields before attempting to log in.
Before: 
![image](https://github.com/12sonam/FreshPicks/assets/119106952/f892a403-1347-4411-88cd-320136ef717f)

After:
![image](https://github.com/12sonam/FreshPicks/assets/119106952/aa7ab80a-c8be-461d-8b23-f02b175e567a)
