### ISSUE TITLE
In Customer and Farmer login page  errors messages are not been displayed properly.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#37]
Do accordingly to the backlog :
[Backlog.docx](https://github.com/12sonam/FreshPicks/files/15324182/Backlog.docx)

**Comment by MaskeyRiddhi** [comment]
I have implemented error messages in the login.js file that display when the email format or password is incorrect.
Before:
![image](https://github.com/12sonam/FreshPicks/assets/119106952/2dacc3a0-588d-4b08-ae74-dfa2d574ea88)
![image](https://github.com/12sonam/FreshPicks/assets/119106952/9a5eb889-368d-4737-b039-42963457743f)

After:
![image](https://github.com/12sonam/FreshPicks/assets/119106952/23d401cd-4171-4b51-bc36-6712e3d9fb23)
![image](https://github.com/12sonam/FreshPicks/assets/119106952/80b44f09-a030-4c68-982a-83d7353d5ec0)
