### ISSUE TITLE
In Farmer Dashboard inside the Product listing page  farmer names are not been displayed.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#38]
if any  problem go through the bug report.

**Comment by MaskeyRiddhi** [comment]
An error occurred while retrieving the farmer data from the database, which was resolved by making corrections in the product.html file. To populate the farmer's name in the dropdown field, some code was added to the addprod.js file.
Before: 
![image](https://github.com/12sonam/FreshPicks/assets/119106952/d4c14c99-c91e-4fa7-9d59-ff709d03db92)

After:
![image](https://github.com/12sonam/FreshPicks/assets/119106952/45b304c3-8412-43dd-8f25-ae31d0751a5c)
