### ISSUE TITLE
On the smaller screen, the sign-up button is being covered and underline on hyperlink in sign-up page need to be removed.

### ISSUE THREAD

**Issue by ShresthaPriya** [12sonam/FreshPicks#4]
When trying to access our program on smaller screen, the sign-up button is being covered. Hence, make sure while making our system responsive,  the sign-up button is not covered and is clearly visible. Moreover, the hyperlink "click here to login as admin" is underlined, make sure to remove that underline.

**Comment by Elizasthaaa** [comment]
I reduced the container size by decreasing the padding allowed the signup button to be displayed effectively on screens narrower than 870 pixels. Furthermore, I eliminated the underline from the hyperlink in the signup page and introduced a orange color to it.

![image](https://github.com/12sonam/FreshPicks/assets/119391309/b09d7684-d118-417f-93bc-a1df0dd38e1b)
![image](https://github.com/12sonam/FreshPicks/assets/119391309/695ed80c-5c37-45e1-a330-5e9ca26a581e)

![image](https://github.com/12sonam/FreshPicks/assets/119391309/0b797e20-8208-4c52-94ac-99c009084f30)
![image](https://github.com/12sonam/FreshPicks/assets/119391309/271088ba-92da-44d1-917c-4247a32a7c16)
