### ISSUE TITLE
Add to cart list and add to  wishlist  sub total is showing nan value.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#40]
Nan value displayed in cartlist sub total and wishlist so solve it.

**Comment by 12sonam** [comment]
![bug](https://github.com/12sonam/FreshPicks/assets/86185394/1eac357d-d703-4763-9ea5-9fbe1f07f225)

the bug has been fixed and when page is refresh the subtotal of the wish list and cart panel does not display NaN it will show the subtotal as below 

![image](https://github.com/12sonam/FreshPicks/assets/86185394/84410e07-5c50-45e4-a8e0-9058b7a9705f)
