### ISSUE TITLE
Admin Dashboard issues

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#5]
According to Backlog, I haven't kept search button in admin dashboard. So remove the search button in Admin Dashboard and also remove messages and password button as it is not mention in backlog.

**Comment by Elizasthaaa** [comment]
In response to the concern raised, the search button in the admin dashboard has been successfully removed. Additionally, the buttons for messages and password in the navigation bar have also been eliminated.
![before](https://github.com/12sonam/FreshPicks/assets/119391309/033ddd08-b151-4595-be7e-962113a31292)
![after](https://github.com/12sonam/FreshPicks/assets/119391309/4ffc6682-fb07-4932-a2be-9dcafd98789f)

**Comment by Elizasthaaa** [comment]
I have mistakely uploaded the same image. This is the final image of admin dashboard after solving the issue.
![images](https://github.com/12sonam/FreshPicks/assets/119391309/72cdf9cd-c21b-4239-9124-be0ff8886e63)
