### ISSUE TITLE
 Admin Login  Error message not displayed 

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#6]
On the admin login page, if the email and password are incorrect, the error message is not displayed.

**Comment by MaskeyRiddhi** [comment]
To solve the issue where the error message is not displayed on the admin login page when both the email and password are incorrect, I modify both the frontend and backend code to ensure proper error handling. In backend (loginadmin.js file), make sure that response from server include the error message in case the authentication fails. In frontend (adminlogin.js file), after the login credentials is send to the server, the response status is checked. if the response status is failure, the error message is thrown. Create div to display the error messages in adminlogin.html file.
Before solving the issues: 
![image](https://github.com/12sonam/FreshPicks/assets/119106952/48d3b4de-5563-4db5-a9da-afaed0c0f26b)
After solving the issues.
![image](https://github.com/12sonam/FreshPicks/assets/119106952/abc42d92-8e46-433f-80c4-ea26bfe2b782)
