### ISSUE TITLE
Signup page error in password 

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#7]
There is a bug in the password section where even if the password format is incorrect, users are still able to sign up.

**Comment by 12sonam** [comment]
Error is fixed and now user can't be able to signup when the password format is incorrect and it will throw a error message.
![image](https://github.com/12sonam/FreshPicks/assets/86185394/47fe9046-3926-4b6f-a488-d2411535e107)
![image](https://github.com/12sonam/FreshPicks/assets/86185394/00b6a5f1-67a3-4cfc-bcf9-fcf540dc1a72)
